In [1]:
import pandas as pd

In [2]:
dem = pd.read_csv('./dem_results.csv').drop(['Unnamed: 0'], axis=1)
dem.columns = ['bigram','count']
rep = pd.read_csv('./rep_results.csv').drop(['Unnamed: 0'], axis=1)
rep.columns = ['bigram','count']
dem = dem.sort_values(by='count', ascending=False).head(200).reset_index().drop(['index'], axis=1)
rep = rep.sort_values(by='count', ascending=False).head(200).reset_index().drop(['index'], axis=1)

In [3]:
inner = pd.merge(dem,rep,on='bigram',how='inner')
inner.columns = ['bigram','dem','rep']
outer = pd.merge(dem,rep,on='bigram',how='outer')
outer.columns = ['bigram','dem','rep']
dem_bigrams = set(dem.bigram)
rep_bigrams = set(rep.bigram)

In [4]:
inner['dem_perc'] = (inner.dem -inner.rep)/inner.rep

In [5]:
inner['rep_perc'] = (inner.rep-inner.dem)/inner.dem

In [9]:
inner.drop(['rep_perc'], axis=1).sort_values('dem_perc', ascending=False).head(12)

                  bigram  dem  rep  dem_perc
14  trump_administration  221   73  2.027397
24          donald_trump  162   55  1.945455
28    senate_republicans  140   56  1.500000
11              trump_'s  264  113  1.336283
31            war_powers  122   55  1.218182
7          public_health  401  191  1.099476
30       trade_agreement  130   62  1.096774
20     local_governments  175   84  1.083333
42    police_departments   95   57  0.666667
3           president_'s  580  394  0.472081
1        president_trump  969  669  0.448430
48          human_rights   78   56  0.392857

In [10]:
inner.drop(['dem_perc'],axis=1).sort_values('rep_perc', ascending=False).head(12)

                  bigram  dem   rep  rep_perc
54        great_american   69   251  2.637681
58     american_outdoors   67   243  2.626866
62          outdoors_act   64   231  2.609375
76        national_parks   54   193  2.574074
9      unanimous_consent  356  1218  2.421348
73        speaker_pelosi   58   190  2.275862
72         national_park   58   181  2.120690
90    protection_program   44   117  1.659091
83   paycheck_protection   48   124  1.583333
46     conservation_fund   84   201  1.392857
43    water_conservation   89   210  1.359551
101    inspector_general   40    91  1.275000

In [14]:
diff = list(dem_bigrams.difference(rep_bigrams))

In [15]:
outer.head(20)

                  bigram     dem     rep
0          united_states  1092.0   940.0
1        president_trump   969.0   669.0
2          mr._president   775.0  1645.0
3           president_'s   580.0   394.0
4        american_people   568.0   785.0
5       small_businesses   476.0   535.0
6        madam_president   449.0   735.0
7          public_health   401.0   191.0
8                 ca_n't   395.0   608.0
9      unanimous_consent   356.0  1218.0
10      leader_mcconnell   308.0     NaN
11           white_house   271.0   210.0
12              trump_'s   264.0   113.0
13             nation_'s   235.0   288.0
14       law_enforcement   222.0   368.0
15  trump_administration   221.0    73.0
16        small_business   219.0   322.0
17     senator_mcconnell   214.0     NaN
18           u.s._senate   203.0   206.0
19    federal_government   195.0   276.0

In [16]:
rep_only = outer[outer.dem.isna()].drop(['dem'],axis=1)
dem_only = outer[outer.rep.isna()].drop(['rep'],axis=1)

In [18]:
rep_only.head(20)

                    bigram    rep
200         senate_proceed  256.0
201        considered_made  223.0
202        house_democrats  209.0
203  democratic_colleagues  183.0
204      democratic_leader  151.0
205        communist_party  148.0
206       morning_business  141.0
207           north_dakota  135.0
208      chinese_communist  123.0
209              hong_kong  106.0
210               house_'s  105.0
211     president_zelensky  104.0
212          mental_health  102.0
213   deferred_maintenance   99.0
214            fiscal_year   99.0
215                 s._res   96.0
216     intervening_action   93.0
217              air_force   90.0
218        considered_read   88.0
219           south_dakota   86.0